### ISSUE TITLE
Mobile CSS for news product

### ISSUE THREAD

**Issue by fmfernandes** [scripting/a8c-FeedLand-Support#28]
This is the CSS code that I added to https://a8c.feedland.org/newsproduct?template=https://drummer.land/fernando.fernandes@automattic.com/newsproduct.opml and @cagrimmett also copied over to https://peekskill.news/:

```css
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;1,300;1,400&display=swap');
body {
	font-family: 'Open Sans', sans-serif;
}
.divRiverSection {
	border-top: none;
}
.divSectionHeader {
	display: flex;
	justify-content: space-between;
	flex-wrap: wrap;
	border-bottom: 1px solid silver;
}
.divRiverSection .spFeedPubDate, .divRiverSection .spFeedTitle {
	margin: unset;
	padding: unset;
	float: unset;
}
.divProductLogo {
	width: unset;
}
.divRiverSection span.spFeedTitle {
	background: white;
}
table, tbody, tr {
	display: block;
}
.divRiverContent {
	background: white;
	border: 1px solid silver;
	box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
	border-radius: 10px;
}
.divRiverItemBody.bodyTruncated {
	-webkit-mask-image: -webkit-gradient(linear, 0 200, 0 110, from(rgba(255, 255, 255, 0)), color-stop(0.6, rgba(255, 255, 255, 0.9)), color-stop(1, rgb(255, 255, 255)), to(rgb(255, 255, 255)));
	transition: max-height 0.2s ease 0s;
}
.divRiverItemBody {
	transition: all 0.2s ease 0s;
}
.divRiverSection .spFeedPubDate {
	background: white;
	order: 2;
}
@media screen and (max-width: 900px ) {
	.divRiverDisplay {
		width: unset;
	}
	.divPageBody {
		width: 95%;
	}
	.divRiverPageTop {
		width: unset;
	}
	.divPageBody {
		margin: 0 auto;
	}
	.divRiverContent {
		width: unset;
	}
	.divRiverPageTop .divProductTitle {
		font-size: 30px;
	}
	.divTitledItem .divTitle {
		font-size: 15px;
	}
	.divTitledItemBody {
		font-size: 13px;
	}
}
```

Would be nice to see it added as the default template for news product as it's a good starting point for mobile screens.
